name: Publish

on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: dotnet publish
      run: dotnet publish -c Release

    - name: publish
      run: | 
        Install-Module -Name PowerShellGet -AllowPrerelease -Force -Scope CurrentUser -SkipPublisherCheck
        Publish-PSResource -Path .\bin\Release\net7.0\publish\RuntimeDiagnostics.psd1 -ApiKey ${{ secrets.APIKEY }}
